---
# tasks file for roles/kubeadm-toolbox
- name: Installing packages
  apt:
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Setting up k8s repo
  block:
    - name: Install apt key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
        dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc

    - name: Add k8s repo
      apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /
        state: present

- name: Installing k8s packages
  apt:
    update_cache: true
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Hold k8s packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl