---
- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    persistent: present
  loop: "{{ kernel_modules }}"

- name: Add kernel parameters to load at boot
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
  loop: "{{ kernel_parameters }}"

- name: Installing packages
  apt:
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg

- name: Setting up Docker repo
  block:
    - name: Install apt key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        #dest: /etc/apt/keyrings/docker.gpg
        dest:  /etc/apt/trusted.gpg.d/docker.asc

    - name: Setting permissions for apt key
      file: 
        name: /etc/apt/trusted.gpg.d/docker.asc
        mode: a+r

    - name: Add docker repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

- name: Installing containerd package
  apt:
    update_cache: true
    name: containerd.io

- name: Set containerd directory
  file:
    name: /etc/containerd/
    state: directory

- name: Check containerd config
  command: grep "SystemdCgroup = true" /etc/containerd/config.toml
  changed_when: no
  ignore_errors: true
  register: check_conf

- name: Generate config.toml for containerd 
  shell: containerd config default | tee /etc/containerd/config.toml
  diff: true
  when: check_conf.rc != 0
  notify: Restart containerd

- name: Enable cgroups for containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: SystemdCgroup = false
    replace: SystemdCgroup = true
  diff: true
  when: check_conf.rc != 0
  notify: Restart containerd

- name: Check containerd status
  command: systemctl status containerd
  changed_when: false